BACKGROUND_COLOR = '#FAFAFA'

CALENDAR_FONT_SIZE = 14

LOGIN_WINDOW_HEIGHT = 220
LOGIN_WINDOW_WIDTH = 300

WINDOW_HEIGHT = 630
WINDOW_WIDTH = 900

NOTES_WINDOW_HEIGHT = 600
NOTES_WINDOW_WIDTH = 300

NEW_NOTE_WINDOW_HEIGHT = 350
NEW_NOTE_WINDOW_WIDTH = 300

ACCOUNT_INFO_WINDOW_HEIGHT = 200
ACCOUNT_INFO_WINDOW_WIDTH = 300
